### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Lampei**
I have updated the library to take advantage of the WebDriver portion of selenium (along with accounting for the Selenium-RC portion).  The Read Me will still need to be updated, but I've added unit tests for the new features and fixed some issues with the previous unit tests.  I've added some comments along the way to try to assist others with issues I ran into when using selenium v1 code.  I've also added the latest selenium jar file and updated all references.

### CODE REVIEW

**Comment by cfmitrah** [comment]
Is this going to merged into master?

**Comment by mattwebdev** [comment]
this looks pretty awesome. im a huge fan of webdriver.

**Comment by DannyCork** [comment]
conflicts need to be resolved before merging, who want's to be a super hero ?

**Comment by mattwebdev** [comment]
I may take a crack at it this weekend.

**Comment by jamiejackson** [comment]
Resolved conflicts in https://github.com/teamcfadvance/CFSelenium/pull/25

@Lampei, could you have a look to see if this is in line with your original intent?

**Comment by Lampei** [comment]
Excellent! @jamiejackson glad someone got around to be able to merge it in. I'd started to get the CI portion going but ran out of time.

**Pull request merged**
